version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - FahadSaleem
  assignees:
  - FahadSaleem
